---
title: "Course on Ecological Trajectory Analysis"
author: "Miquel De Cáceres, Anthony Sturbois, Nicolas Djeghri"
output: github_document
---

## Introduction

This repository contains a course devoted to learn the Ecological Trajectory Analysis (ETA) framework using the **ecotraj** package. The course is presented as a set of Quarto markdown (`*.qmd`) files, which can be easily deployed into html format.

Course sessions are updated to the most recent course edition and package versions.

## Usage

The course slides are made using [Quarto](https://quarto.org/). This publishing system should be installed in order to recreate and modify course slides.

## Course sessions

Code for course sessions is in `sessions/*.qmd` files. Printed `sessions/pdf/*.pdf` files can also be found.

1. Introduction to Ecological Trajectory Analysis
2. Exploring the potential of ETA on different multivariate spaces
3. Introduction to Cyclical Ecological Trajectory Analysis

## Ancillary files

These are required to recreate slide presentations from `*.qmd` files.

+ `sessions/resources/scss` contains style sheets that customize slide appearance. 
+ `sessions/resources/img` contains figures in PNG, SVG or JPG format used in slides.

## Exercises

Exercises are included in a separate folder.

+ `exercises/guidelines/Exercise_*.Rmd` are guidelines for exercises
+ `exercises/solutions/Exercise_*_solution.Rmd` are solutions for exercises
+ `exercises/StudentRdata/*.rds` are data sets required for exercises
+ `exercises/R/*.R` are files to prepare data for exercises

The proposed exercises are the following:

|  Exercise | Purpose                                                 |
|-----------|---------------------------------------------------------|
| exercise CETA | Practice CETA on a real example of zooplancton community dynamics |


## Course editions

Three different course editions have been held so far:

#### First edition (May 2025)

  + *Dates*: 13th May 2025
  + *Location*: Technopole Brest-Iroise (Plouzané, France)
  + *Organizer*: NEST hub
  + *Lecturers*: Miquel De Cáceres, Anthony Sturbois, Nicolas Djeghri

#### Second edition (Feb 2026)

  + *Dates*: 24-25th Feb 2026
  + *Location*: UAB (Cerdanyola del Vallès, Spain)
  + *Organizer*: CREAF
  + *Lecturers*: Miquel De Cáceres, Javier de la Casa